Migrate from Jenkins -> GitHub Actions
typecode/sykle pull request #71
Opened 2021-09-30 16:15 UTC by emmabh

2021-10-12 17:59 UTC, Didericis commented on .github/workflows/ci.yml
> +          for file in sykle/plugins/**/requirements.txt; do
👍  nice little bash snippet

2021-10-12 17:59 UTC, Didericis approved these changes, later dismissed

2021-10-12 18:03 UTC, Didericis commented on .github/workflows/cd.yml
> +name: CD
@emmabh this can actually be removed; originally, when we had most of our projects on jenkins, this would ensure that a push to this repo would automatically update jenkins so that the internal `syk` command available on that jenkins instance was up to date. So the `sudo make install` command that was previously running on jenkins was just for that instance.

2021-10-12 18:04 UTC, Didericis requested changes
CD workflow can be removed/is no longer necessary, otherwise LGTM

2021-10-14 15:03 UTC, emmabh commented on .github/workflows/cd.yml
> +name: CD
a-ha! that makes total sense, I was wondering why we had a cd that didn't go anywhere but it all makes sense now lol.

2024-09-14 23:17 UTC, Didericis approved these changes

2025-06-24 20:35 UTC, merged